### ISSUE TITLE
Code failing with AttributeError: 'Tensor' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by pujari-rajkumar** [Maluuba/mctest-model#12]
python2.7 run.py 
Using TensorFlow backend.
init dataset with h5 file.
(u'input_answer_shape:', (600, 4, 24))
(u'input_dep_shape:', (600, 51, 4))
(u'input_dep_2gram_shape:', (600, 50, 4))
(u'input_dep_3gram_shape:', (600, 49, 4))
(u'input_negation_questions_shape:', (600, 4))
(u'input_question_shape:', (600, 19))
(u'input_question_answer_shape:', (600, 4, 26))
(u'input_reordered_story_shape:', (600, 51, 83))
(u'input_reordered_story_2gram_shape:', (600, 50, 98))
(u'input_reordered_story_3gram_shape:', (600, 49, 141))
(u'input_reordered_story_attentive_shape:', (600, 632))
(u'input_story_shape:', (600, 51, 83))
(u'input_story_2gram_shape:', (600, 50, 98))
(u'input_story_3gram_shape:', (600, 49, 141))
(u'input_story_attentive_shape:', (600, 632))
(u'y_hat_shape:', (600, 4))
INFO:__main__:finish init dataset with data.h5
INFO:embeddings:load mode=in-memory, embedding data type=<type 'numpy.ndarray'>, shape=(3000000, 300)
loading word embedding.
2018-11-20 15:09:13.013095: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-20 15:09:13.013120: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-20 15:09:13.013126: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-11-20 15:09:13.013130: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-20 15:09:13.013135: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "run.py", line 92, in <module>
    train_option(EPOCHS=args.epoch)
  File "run.py", line 72, in train_option
    graph = model.build()
  File "/u/scratch1/rpujari/parallel_hierarchical/model.py", line 623, in build
    self._add_sentence_encode(encode=self.model_config['layers']['sentence_encode']['type'])
  File "/u/scratch1/rpujari/parallel_hierarchical/model.py", line 246, in _add_sentence_encode
    nodes['__story_encoding1'] = weighting_layer([nodes['story_word_embedding1'], nodes['__w_story1']])
  File "/homes/rpujari/anaconda3/envs/flower/lib/python2.7/site-packages/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/homes/rpujari/anaconda3/envs/flower/lib/python2.7/site-packages/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/homes/rpujari/anaconda3/envs/flower/lib/python2.7/site-packages/keras/engine/topology.py", line 153, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors, mask=input_masks))
  File "/u/scratch1/rpujari/parallel_hierarchical/layers.py", line 282, in call
    lay1 = T.addbroadcast(lay1, lay1.ndim - 1)
AttributeError: 'Tensor' object has no attribute 'ndim'

**Comment by pujari-rajkumar** [comment]
I was using a Tensorflow backend while I should have been using Theano backend.
