### ISSUE TITLE
run.py failing on `AttributeError`

### ISSUE THREAD

**Issue by lispsteve** [Maluuba/mctest-model#4]
Following the instructions, using a python2.7 anaconda distribution with Keras 1.1.1 and Then 0.8.2 I get the following failure. 
 
```
(python2) user@localhost:maluuba/mctest-model$ time python run.py
Using Theano backend.
init dataset with h5 file.
(u'input_answer_shape:', (600, 4, 24))
(u'input_dep_shape:', (600, 51, 4))
(u'input_dep_2gram_shape:', (600, 50, 4))
(u'input_dep_3gram_shape:', (600, 49, 4))
(u'input_negation_questions_shape:', (600, 4))
(u'input_question_shape:', (600, 19))
(u'input_question_answer_shape:', (600, 4, 26))
(u'input_reordered_story_shape:', (600, 51, 83))
(u'input_reordered_story_2gram_shape:', (600, 50, 98))
(u'input_reordered_story_3gram_shape:', (600, 49, 141))
(u'input_reordered_story_attentive_shape:', (600, 632))
(u'input_story_shape:', (600, 51, 83))
(u'input_story_2gram_shape:', (600, 50, 98))
(u'input_story_3gram_shape:', (600, 49, 141))
(u'input_story_attentive_shape:', (600, 632))
(u'y_hat_shape:', (600, 4))
INFO:__main__:finish init dataset with data.h5
INFO:embeddings:load mode=in-memory, embedding data type=<type 'numpy.ndarray'>, shape=(3000000, 300)
loading word embedding.
Traceback (most recent call last):
  File "run.py", line 92, in <module>
    train_option(EPOCHS=args.epoch)
  File "run.py", line 72, in train_option
    graph = model.build()
  File "mctest-model/model.py", line 624, in build
    self._add_model()
  File "mctest-model/model.py", line 417, in _add_model
    trainable=config['trainable_sentence_ensemble'])(layers_s_input)
  File "mctest-model/layers.py", line 594, in __init__
    self.weights = weights if len(weights) == layers_len else [1.] * layers_len
AttributeError: can't set attribute
```

**Comment by lispsteve** [comment]
Actually downgrading to keras 1.0.2 seemed to do the trick.
